<#
.SYNOPSIS
    Weekly Snapshot — Aggregates the week's signals into a single summary
.DESCRIPTION
    Scans all signal files from the past 7 days (or since last snapshot)
    and creates a consolidated weekly summary in Weekly_Snapshots/.
    Best run on Fridays or Monday mornings.
#>

param(
    [int]$DaysBack = 7,
    [switch]$DryRun,
    [switch]$Force
)

$ErrorActionPreference = "Continue"
$ROOT = Split-Path -Parent $PSScriptRoot
$SIGNALS_DIR = Join-Path $ROOT "00_Daily_Intelligence\Signals"
$SNAPSHOTS_DIR = Join-Path $ROOT "00_Daily_Intelligence\Weekly_Snapshots"
$TODAY = Get-Date -Format "yyyy-MM-dd"
$WEEK_START = (Get-Date).AddDays(-$DaysBack).ToString("yyyy-MM-dd")
$OUTPUT_FILE = Join-Path $SNAPSHOTS_DIR "${TODAY}_Weekly_Snapshot.md"

if (-not (Test-Path $SNAPSHOTS_DIR)) {
    New-Item -ItemType Directory -Path $SNAPSHOTS_DIR -Force | Out-Null
}

if ($DryRun) {
    Write-Host "[DRY RUN] Would generate weekly snapshot for $WEEK_START to $TODAY"
    Write-Host "[DRY RUN] Output: $OUTPUT_FILE"
    return
}

# ── Guard: skip if snapshot already exists for this week ─────────────────────
if ((Test-Path $OUTPUT_FILE) -and -not $Force) {
    Write-Host "Weekly snapshot already exists for today ($TODAY). Use -Force to override."
    return
}
$weekStart = (Get-Date).AddDays(-((Get-Date).DayOfWeek.value__ + 1) % 7).Date
$existingThisWeek = Get-ChildItem $SNAPSHOTS_DIR -Filter "*Weekly_Snapshot.md" -ErrorAction SilentlyContinue |
    Where-Object { $_.LastWriteTime -ge $weekStart }
if ($existingThisWeek -and -not $Force) {
    Write-Host "Weekly snapshot already exists this week ($($existingThisWeek.Name)). Use -Force to override."
    return
}

# ── Collect signals ──────────────────────────────────────────────────────────
$cutoff = (Get-Date).AddDays(-$DaysBack)
$signalFiles = @()
if (Test-Path $SIGNALS_DIR) {
    $signalFiles = Get-ChildItem $SIGNALS_DIR -File | Where-Object { $_.LastWriteTime -ge $cutoff } | Sort-Object Name
}

# ── Build snapshot ───────────────────────────────────────────────────────────
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Weekly Snapshot: $WEEK_START to $TODAY")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine("Signal files aggregated: $($signalFiles.Count)")
[void]$sb.AppendLine("")

# Group by type
$types = @("emails", "ado", "calendar", "chats", "inbox_parsed")
foreach ($type in $types) {
    $typeFiles = $signalFiles | Where-Object { $_.Name -like "${type}_*" }
    if ($typeFiles.Count -gt 0) {
        $displayName = switch ($type) {
            "emails"       { "Email Signals" }
            "ado"          { "ADO Work Items" }
            "calendar"     { "Calendar Events" }
            "chats"        { "Teams Chats" }
            "inbox_parsed" { "Inbox Parsed Files" }
        }
        [void]$sb.AppendLine("## $displayName ($($typeFiles.Count) days)")
        [void]$sb.AppendLine("")
        foreach ($f in $typeFiles) {
            $date = if ($f.Name -match '\d{4}-\d{2}-\d{2}') { $Matches[0] } else { $f.Name }
            [void]$sb.AppendLine("### $date")
            [void]$sb.AppendLine("")
            $content = Get-Content $f.FullName -Raw -ErrorAction SilentlyContinue
            if ($content) {
                $lines = $content -split "`n" | Where-Object { $_ -match "^[-*]|^##|^\d+\." } | Select-Object -First 30
                if ($lines) {
                    [void]$sb.AppendLine(($lines -join "`n"))
                } else {
                    [void]$sb.AppendLine("*(Signal file present but no structured data extracted)*")
                }
            } else {
                [void]$sb.AppendLine("*(Empty or unreadable)*")
            }
            [void]$sb.AppendLine("")
        }
    }
}

# ── Briefs summary ──────────────────────────────────────────────────────────
$BRIEFS_DIR = Join-Path $ROOT "00_Daily_Intelligence\Daily_Briefs"
if (Test-Path $BRIEFS_DIR) {
    $briefFiles = Get-ChildItem $BRIEFS_DIR -File | Where-Object { $_.LastWriteTime -ge $cutoff } | Sort-Object Name
    if ($briefFiles.Count -gt 0) {
        [void]$sb.AppendLine("## Daily Briefs ($($briefFiles.Count) days)")
        [void]$sb.AppendLine("")
        foreach ($f in $briefFiles) {
            [void]$sb.AppendLine("- $($f.Name)")
        }
        [void]$sb.AppendLine("")
    }
}

# ── Stats footer ─────────────────────────────────────────────────────────────
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("*Generated by weekly_snapshot.ps1 | Brain OS Workspace Automation*")

# ── Write output ─────────────────────────────────────────────────────────────
$sb.ToString() | Out-File -FilePath $OUTPUT_FILE -Encoding utf8 -Force
Write-Host "Weekly snapshot saved: $OUTPUT_FILE"
Write-Host "Aggregated $($signalFiles.Count) signal files from $WEEK_START to $TODAY"
